# Minecraft Server: CraftBukkit
#
# VERSION 1.7.2-R0.1
FROM zenexer/minecraft-base
MAINTAINER Paul Buonopane <paul+docker@earth2me.com>

RUN curl -o /mc/server.jar 'http://dl.bukkit.org/downloads/craftbukkit/get/02430_1.7.2-R0.1/craftbukkit-dev.jar'