# Minecraft Server: Base
#
# VERSION 1.0.0
FROM stackbrew/ubuntu:saucy
MAINTAINER Paul Buonopane <paul+docker@earth2me.com>

RUN apt-get update
RUN apt-get install -y openjdk-7-jre curl

RUN echo 'server.jar is required for this container to run.' > /mc/server.jar.REQUIRED