#!/bin/bash
# Default configuration settings.  Use this as a reference when configuring the
# application.

# Basic config {{{1
#      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#      !! WARNING: DO NOT EDIT THIS FILE.  This is just a reference.  Edit !!
#      !! config.local.sh instead.                                         !!
#      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

config=(
	# Changing this will break updates/upgrades.  Keep this as it is.
	[jar]='server.jar'

	# Path to a specific java binary.  Recommended to use update-alternatives
	# instead of changing this.
	[java]=java

	# Memory available for the JVM heap.  You can use $memory_kb and $memory_mb
	# to get the total available memory for the system, but keep in mind that
	# containers share the same memory pool.  $default_{min,max}_heap are
	# considered sane values for typical servers, with a 2 GiB memory cap.  If
	# you need more than that, either you have hundreds of players, or you're
	# doing something wrong.
	[java_min_heap]=$default_min_heap
	[java_max_heap]=$default_max_heap


	# You shouldn't need to mess with this stuff. {{{
	#
	#

	[input_stream]="${dirs[tmp]}/input.stream"
	[output_stream]="${dirs[tmp]}/output.stream"

	#
	#
	# }}}
)


# Complex configuration {{{1
#     Some configuration settings need to be derived from others, and may be
#     complex types that cannot be values in an associative array.

# Use this format to add additional java arguments.  Note the += operator.
# Don't add -Xms or -Xmx!  Those are added automatically.
config_java_args+=(
)